name: symfony8-2305TC
volumes:
  db_data: {}
services:
  db:
    image: mariadb:10.8.5
    container_name: symfony8-2305TC-db
    restart: unless-stopped
    ports: [ "3366:3306" ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
  web:
   # image: php:8.4-apache
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: symfony8-2305TC-web
    restart: unless-stopped
    ports: ["8877:80"]
    depends_on: ['db']
    links: ['db']
    volumes:
      - ./src:/var/www/html

      
